<div id="confirmModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content panel-danger">
            <div class="modal-header panel-heading">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title modal-sm">Confirmation required</h4>
            </div>
            <div class="modal-body">
                <p>Do you really want to commit this action?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" id="confirmButton" data-dismiss="modal">Yes</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
